# Cloud-Only Google Cloud Build configuration for Na Winie
# Optimized for Google Cloud Run deployment without local development support

steps:
  # Build the Docker image with cloud-only configuration
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--file'
      - 'Dockerfile.cloud'
      - '--build-arg'
      - 'PUBLIC_SUPABASE_URL=${_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'PUBLIC_SUPABASE_ANON_KEY=${_PUBLIC_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'PUBLIC_USE_LOCAL_BACKEND=false'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/nawinie-cloud:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/nawinie-cloud:latest'
      - '.'

  # Push the images to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/nawinie-cloud:${SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/nawinie-cloud:latest']

  # Deploy to Cloud Run (environment variables managed in Cloud Console)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nawinie'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/nawinie-cloud:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '100'
      - '--timeout'
      - '300'
      - '--port'
      - '8080'

# Build-time substitutions (only for frontend build)
substitutions:
  _PUBLIC_SUPABASE_URL: 'REQUIRED'  # Set this to your Supabase URL (for frontend build)
  _PUBLIC_SUPABASE_ANON_KEY: 'REQUIRED'  # Set this to your Supabase anon key (for frontend build)
  _REGION: 'us-central1'  # Google Cloud region

# Images will be stored in Google Container Registry with cloud suffix
images: 
  - 'gcr.io/${PROJECT_ID}/nawinie-cloud:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/nawinie-cloud:latest'

# Build options optimized for cloud deployment
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY
  
# Cloud Build timeout
timeout: '1200s'  # 20 minutes 