apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nawinie
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/description: "Na Winie Cloud-Only Deployment"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-boost: true
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: true
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: PROJECT_NUMBER-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/nawinie-cloud:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        # Cloud Run Configuration
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "production"
        
        # JWT Configuration (Use Secret Manager in production)
        - name: JWT_SECRET_KEY
          value: "REPLACE_WITH_YOUR_JWT_SECRET_KEY"
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        
        # Supabase Configuration
        - name: PUBLIC_SUPABASE_URL
          value: "https://YOUR_PROJECT_ID.supabase.co"
        - name: PUBLIC_SUPABASE_ANON_KEY
          value: "REPLACE_WITH_YOUR_SUPABASE_ANON_KEY"
        - name: SUPABASE_URL
          value: "https://YOUR_PROJECT_ID.supabase.co"
        - name: SUPABASE_ANON_KEY
          value: "REPLACE_WITH_YOUR_SUPABASE_ANON_KEY"
        - name: SUPABASE_SERVICE_ROLE_KEY
          value: "REPLACE_WITH_YOUR_SUPABASE_SERVICE_ROLE_KEY"
        
        # Database Configuration
        - name: DATABASE_URL
          value: "REPLACE_WITH_YOUR_DATABASE_URL"
        
        # Application Configuration
        - name: PUBLIC_USE_LOCAL_BACKEND
          value: "false"
        - name: CORS_ORIGINS
          value: "https://your-domain.com"
        
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3

---
# Optional: IAM Policy for public access
apiVersion: v1
kind: ConfigMap
metadata:
  name: nawinie-iam-policy
data:
  policy.yaml: |
    bindings:
    - members:
      - allUsers
      role: roles/run.invoker 